name: ControlFinanceV3

services:
  db:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    restart: unless-stopped
    ports:
      - "${DB_EXPORT_PORT}:${DB_INTERNAL_PORT}" # externa/interna